kind: Config
apiVersion: v1
preferences:
  colors: true
clusters:
- name: allinone
  cluster:
    server: https://localhost:6443
    api-version: v1
    insecure-skip-tls-verify: false
    certificate-authority:  ./cert-authn/ca.pem
users:
- name: kube-proxy
  user:
    client-certificate: ./cert-authn/cert.pem
    client-key: ./cert-authn/key.pem
contexts:
- name: allinone-kube-proxy
  context:
    cluster: allinone
    user: kube-proxy
    namespace: default

current-context: allinone-kube-proxy
