kind: Config
apiVersion: v1
preferences:
  colors: true
clusters:
- name: allinone
  cluster:
    server: https://192.168.40.99:6443
    api-version: v1
    insecure-skip-tls-verify: false
    certificate-authority:  ../../../../AuthnAuthz/apiserver/ca/ca.pem
users:
- name: kube-controller-manager
  user:
    client-certificate: ../../../../AuthnAuthz/authn/users/kube-controller-manager/Cert/cert.pem
    client-key: ../../../../AuthnAuthz/authn/users/kube-controller-manager/Cert/key.pem
contexts:
- name: allinone-kube-controller-manager
  context:
    cluster: allinone
    user: kube-controller-manager
    namespace: default

current-context: allinone-kube-controller-manager
