apiVersion: v1
kind: LimitRange
metadata:
  name: kube-system-limits
spec:
  limits:
  - max:
      cpu: "2"
      memory: 1Gi
      storage: 20Gi
    min:
      cpu: 50m
      memory: 6Mi
      storage: 5Gi
    type: Pod
  - default:
      cpu: 250m
      memory: 100Mi
      storage: 5Gi
    max:
      cpu: "2"
      memory: 1Gi
      storage: 20Gi
    min:
      cpu: 50m
      memory: 6Mi
      storage: 5Gi
    type: Container
