---
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata: 
    labels: 
      name: "kubedash"
    name: "kubedash"
    namespace: "kube-system"
  spec: 
    replicas: 1
    selector: 
      name: "kubedash"
    template: 
      metadata: 
        labels: 
          name: "kubedash"
      spec: 
        containers: 
          - image: "localhost:5000/honeycomb/kubedash:v0.2.1"
            name: "kubedash"
            command: 
              - /entrypoint.sh
#            resources:
#              limits:
#                cpu: 50m
#                memory: 100MB
            volumeMounts: 
              - 
                name: "ssl-certs"
                mountPath: "/etc/ssl/certs"
                readOnly: true
        volumes: 
          - 
            name: "ssl-certs"
            hostPath: 
              path: "/etc/ssl/certs"

---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    labels: 
      name: "kubedash"
    name: "kubedash"
    namespace: "kube-system"
  spec:
    type: "ClusterIP"
    ports: 
      - 
        port: 80
        targetPort: 8289
    selector: 
      name: "kubedash"
