version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        layerinfo: inmemory
    filesystem:
        rootdirectory: ./Data/registry
http:
    addr: 192.168.40.99:5000
    tls: 
        certificate: ./certs/registry.local/cert.pem
        key: ./certs/registry.local/key.pem
