kind: Config
apiVersion: v1
preferences:
  colors: true
clusters:
- name: allinone
  cluster:
    server: https://apiserver.local
    api-version: v1
    insecure-skip-tls-verify: false
    certificate-authority:  ../apiserver.ca
users:
- name: {USER}
  user:
    client-certificate: ./Cert/cert.pem
    client-key: ./Cert/key.pem
contexts:
- name: allinone-{USER}
  context:
    cluster: allinone
    user: {USER}
    namespace: default

current-context: allinone-{USER}
