kind: Config
apiVersion: v1
preferences:
  colors: true
clusters:
- name: allinone
  cluster:
    server: https://apiserver.local
    api-version: v1
    insecure-skip-tls-verify: false
    certificate-authority:  ./certs/apiserver.ca
users:
- name: kube-controller-manager
  user:
    client-certificate: ./certs/authn.cert
    client-key: ./certs/authn.key
contexts:
- name: allinone-kube-controller-manager
  context:
    cluster: allinone
    user: kube-controller-manager
    namespace: default

current-context: allinone-kube-controller-manager
