kind: Config
apiVersion: v1
preferences:
  colors: true
clusters:
- name: allinone
  cluster:
    server: https://localhost:6443
    api-version: v1
    insecure-skip-tls-verify: false
    certificate-authority:  ../ca/ca.pem
users:
- name: {USER}
  user:
    client-certificate: ./cert.pem
    client-key: ./key.pem
contexts:
- name: allinone-{USER}
  context:
    cluster: allinone
    user: {USER}
    namespace: default

current-context: allinone-{USER}
