kind: Config
apiVersion: v1
preferences:
  colors: true
clusters:
- name: allinone
  cluster:
    server: https://apiserver.local
    api-version: v1
    insecure-skip-tls-verify: false
    certificate-authority:  ../apiserver.ca
users:
- name: admin-super
  user:
    client-certificate: ./Cert/cert.pem
    client-key: ./Cert/key.pem
contexts:
- name: allinone-admin-super
  context:
    cluster: allinone
    user: admin-super
    namespace: default

current-context: allinone-admin-super
