kind: Config
apiVersion: v1
preferences:
  colors: true
clusters:
- name: allinone
  cluster:
    server: http://apiserver.local
    api-version: v1
    insecure-skip-tls-verify: yes
users:
- name: kube-scheduler
  user:
contexts:
- name: allinone-kube-scheduler
  context:
    cluster: allinone
    user: kube-scheduler
    namespace: default

current-context: allinone-kube-scheduler
