apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v6
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v6
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: localhost:5000/honeycomb/heapster:v0.18.2
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes:?useServiceAccount=true&kubeletHttps=false
            - --sink=influxdb:http://${MONITORING_INFLUXDB_SERVICE_HOST}:8086
            - -logtostderr=true
            - -v=2
